# Generated by Django 5.2.8 on 2026-05-27 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('investigator', models.CharField(max_length=160)),
                ('department', models.CharField(default='Gujarat Cyber Crime Cell', max_length=160)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('report-ready', 'Report ready')], default='open', max_length=32)),
                ('priority', models.CharField(choices=[('Standard', 'Standard'), ('Urgent', 'Urgent'), ('Critical', 'Critical')], default='Standard', max_length=32)),
                ('report_status', models.CharField(default='draft', max_length=32)),
                ('source_location', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_name', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(default='mocked', max_length=32)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('linked_cases_count', models.PositiveIntegerField(default=0)),
                ('api_mode', models.CharField(max_length=160)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaptureJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('stored_pcap', 'Stored PCAP'), ('live_capture', 'Live Capture'), ('log_import', 'Log Import')], max_length=32)),
                ('interface_name', models.CharField(blank=True, max_length=80)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('packet_limit', models.PositiveIntegerField(default=0)),
                ('bpf_filter', models.CharField(blank=True, max_length=255)),
                ('source_ip_filter', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip_filter', models.CharField(blank=True, max_length=255)),
                ('protocol_filter', models.CharField(blank=True, max_length=40)),
                ('port_filter', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('packets_captured', models.PositiveIntegerField(default=0)),
                ('bytes_captured', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_jobs', to='forensics.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnomalyRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=160)),
                ('behaviour', models.CharField(max_length=160)),
                ('baseline', models.CharField(max_length=160)),
                ('observed', models.CharField(max_length=160)),
                ('deviation', models.CharField(max_length=80)),
                ('confidence', models.PositiveIntegerField(default=0)),
                ('hypothesis', models.CharField(max_length=160)),
                ('model_version', models.CharField(default='scikit-v1', max_length=80)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='forensics.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('attack_class', models.CharField(max_length=80)),
                ('alert_type', models.CharField(max_length=255)),
                ('source_ip', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=40)),
                ('event_timestamp', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='new', max_length=32)),
                ('explanation', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='forensics.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_label', models.CharField(max_length=160)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Investigator', 'Investigator'), ('Analyst', 'Analyst'), ('Viewer', 'Viewer')], max_length=32)),
                ('action', models.CharField(max_length=160)),
                ('resource_type', models.CharField(blank=True, max_length=80)),
                ('resource_id', models.CharField(blank=True, max_length=160)),
                ('result', models.CharField(default='allowed', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='forensics.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_name', models.CharField(max_length=160)),
                ('action', models.CharField(max_length=160)),
                ('details', models.TextField()),
                ('event_hash', models.CharField(blank=True, max_length=64)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='forensics.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=160)),
                ('status', models.CharField(max_length=32)),
                ('detail', models.TextField()),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_controls', to='forensics.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetectionMatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=80)),
                ('matched_entity', models.CharField(max_length=160)),
                ('confidence', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='new', max_length=32)),
                ('explanation', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_matches', to='forensics.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=500)),
                ('evidence_type', models.CharField(choices=[('PCAP', 'PCAP'), ('Firewall Logs', 'Firewall Logs'), ('DNS Logs', 'DNS Logs'), ('TLS Metadata', 'TLS Metadata'), ('Mixed Evidence', 'Mixed Evidence')], default='PCAP', max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('processing', 'Processing'), ('failed', 'Failed')], default='verified', max_length=32)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='forensics.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('export_type', models.CharField(max_length=80)),
                ('requested_by', models.CharField(max_length=160)),
                ('stored_path', models.CharField(blank=True, max_length=500)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='forensics.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('step', models.CharField(default='queued', max_length=80)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='forensics.case')),
                ('evidence_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='forensics.evidencefile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('language', models.CharField(default='en', max_length=20)),
                ('generated_by', models.CharField(max_length=160)),
                ('stored_path', models.CharField(blank=True, max_length=500)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='ready', max_length=32)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forensics.case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=40)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('packet_count', models.PositiveIntegerField(default=0)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('related_alert_ids', models.JSONField(blank=True, default=list)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='forensics.case')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
