# Generated by Django 5.2.8 on 2026-06-01 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0005_phase5_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('encrypted_source_path', models.CharField(max_length=500)),
                ('plaintext_sha256', models.CharField(max_length=64)),
                ('packet_count', models.PositiveIntegerField(default=0)),
                ('byte_count', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('parser_completed_at', models.DateTimeField(blank=True, null=True)),
                ('decoder_completed_at', models.DateTimeField(blank=True, null=True)),
                ('session_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisStageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=32)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaptureSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('enabled', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('one-time', 'One time'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=24)),
                ('start_at', models.DateTimeField()),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=80)),
                ('weekdays_json', models.JSONField(blank=True, default=list)),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('packet_limit', models.PositiveIntegerField(default=10000)),
                ('chunk_interval_seconds', models.PositiveIntegerField(default=5)),
                ('interface_name', models.CharField(max_length=255)),
                ('bpf_filter', models.CharField(blank=True, max_length=255)),
                ('case_id_prefix', models.CharField(default='CYB-GJ-SCHEDULED', max_length=80)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetentionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.CharField(max_length=160)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('legal_hold', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('skipped', 'Skipped'), ('deleted', 'Deleted'), ('requires-approval', 'Requires approval')], default='pending', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('high_volume_search_days', models.PositiveIntegerField(default=30)),
                ('evidence_days', models.PositiveIntegerField(default=90)),
                ('capture_chunk_days', models.PositiveIntegerField(default=7)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetentionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(default='preview', max_length=32)),
                ('status', models.CharField(default='running', max_length=32)),
                ('candidates_json', models.JSONField(blank=True, default=list)),
                ('deleted_json', models.JSONField(blank=True, default=list)),
                ('bytes_reclaimed', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SensorCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_type', models.CharField(max_length=80)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=24)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#2563eb', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SensorHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=24)),
                ('heartbeat_age_seconds', models.PositiveIntegerField(default=0)),
                ('capture_engine', models.CharField(blank=True, max_length=160)),
                ('interface_count', models.PositiveIntegerField(default=0)),
                ('current_job_id', models.CharField(blank=True, max_length=80)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='capturechunk',
            name='retention_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='legal_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='legal_hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='legal_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='retention_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='completed_chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='completeness_status',
            field=models.CharField(default='complete', max_length=40),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='expected_chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='fallback_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='last_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='processing_path',
            field=models.CharField(default='sync-fallback', max_length=32),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='source_capture_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='forensics.capturejob'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='stage_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='current_capture_job',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sensor',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_command_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sensor',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='tags_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sensor',
            name='total_bytes_uploaded',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='total_chunks_uploaded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('stale', 'Stale'), ('offline', 'Offline'), ('disabled', 'Disabled'), ('capturing', 'Capturing'), ('warning', 'Warning')], default='online', max_length=24),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['created_at'], name='netra_access_created_idx'),
        ),
        migrations.AddIndex(
            model_name='capturechunk',
            index=models.Index(fields=['created_at', 'status'], name='netra_chunk_created_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='capturejob',
            index=models.Index(fields=['sensor', 'status', 'created_at'], name='netra_cap_sensor_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='custodyledgerevent',
            index=models.Index(fields=['case', 'created_at'], name='netra_custody_case_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalevent',
            index=models.Index(fields=['created_at'], name='netra_ops_created_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'updated_at'], name='netra_job_status_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['case', 'created_at'], name='netra_job_case_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workerheartbeat',
            index=models.Index(fields=['worker_name', 'last_seen_at'], name='netra_worker_seen_idx'),
        ),
        migrations.AddField(
            model_name='analysischunk',
            name='processing_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_chunks', to='forensics.processingjob'),
        ),
        migrations.AddField(
            model_name='analysisstageresult',
            name='analysis_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_results', to='forensics.analysischunk'),
        ),
        migrations.AddField(
            model_name='analysisstageresult',
            name='processing_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_results', to='forensics.processingjob'),
        ),
        migrations.AddField(
            model_name='captureschedule',
            name='last_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_runs', to='forensics.capturejob'),
        ),
        migrations.AddField(
            model_name='captureschedule',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_schedules', to='forensics.sensor'),
        ),
        migrations.AddField(
            model_name='retentioncandidate',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_candidates', to='forensics.case'),
        ),
        migrations.AddField(
            model_name='sensorcommand',
            name='capture_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_commands', to='forensics.capturejob'),
        ),
        migrations.AddField(
            model_name='sensorcommand',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='forensics.sensor'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='forensics.sensorgroup'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['status', 'last_heartbeat_at'], name='netra_sensor_health_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['group', 'status'], name='netra_sensor_group_stat_idx'),
        ),
        migrations.AddField(
            model_name='sensorhealthsnapshot',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='forensics.sensor'),
        ),
        migrations.AddIndex(
            model_name='analysischunk',
            index=models.Index(fields=['status', 'created_at'], name='netra_analysis_chunk_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analysischunk',
            unique_together={('processing_job', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='sensorcommand',
            index=models.Index(fields=['sensor', 'status', 'issued_at'], name='netra_sensor_cmd_stat_idx'),
        ),
    ]
