# Generated by Django 5.2 on 2026-07-14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forensics", "0011_processingjob_attempt_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceUploadSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_user_id", models.CharField(db_index=True, max_length=128)),
                ("organization", models.CharField(max_length=160)),
                ("expected_filename", models.CharField(max_length=255)),
                ("expected_size_bytes", models.BigIntegerField()),
                ("expected_evidence_type", models.CharField(max_length=64)),
                ("expected_content_type", models.CharField(default="application/octet-stream", max_length=160)),
                ("storage_path", models.CharField(max_length=500, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("uploading", "Uploading"),
                            ("uploaded", "Uploaded"),
                            ("finalized", "Finalized"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        default="created",
                        max_length=32,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("fingerprint", models.CharField(max_length=64)),
                ("actual_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("actual_content_type", models.CharField(blank=True, max_length=160)),
                ("actual_sha256", models.CharField(blank=True, max_length=64)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("intake_json", models.JSONField(blank=True, default=dict)),
                ("normalization_json", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                (
                    "case",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="upload_sessions", to="forensics.case"),
                ),
                (
                    "processing_job",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="upload_sessions", to="forensics.processingjob"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="netra_upload_sessions", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "status"], name="netra_upload_user_status_idx"),
                    models.Index(fields=["organization", "status"], name="netra_upload_org_status_idx"),
                    models.Index(fields=["expires_at", "status"], name="netra_upload_expiry_idx"),
                    models.Index(fields=["case", "created_at"], name="netra_upload_case_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(status__in=["created", "uploading", "uploaded", "finalized", "queued", "processing"]),
                        fields=("user",),
                        name="netra_one_active_upload_user",
                    ),
                ],
            },
        ),
    ]
