# Generated by Django 5.2.16 on 2026-08-09 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_integration_organizations(apps, _schema_editor):
    IntegrationConnection = apps.get_model("forensics", "IntegrationConnection")
    IntegrationDelivery = apps.get_model("forensics", "IntegrationDelivery")
    Organization = apps.get_model("forensics", "Organization")

    organization_ids = list(Organization.objects.order_by().values_list("id", flat=True))
    for connection in IntegrationConnection.objects.order_by("pk").iterator():
        linked_organizations = list(
            IntegrationDelivery.objects.filter(integration_id=connection.pk, case__isnull=False)
            .order_by()
            .values_list("case__organization_id", flat=True)
            .distinct()
        )
        if len(linked_organizations) > 1:
            raise RuntimeError(
                f"Integration {connection.pk} has deliveries in multiple organizations; tenant backfill aborted."
            )
        if linked_organizations:
            organization_id = linked_organizations[0]
        elif len(organization_ids) == 1:
            organization_id = organization_ids[0]
        else:
            raise RuntimeError(
                f"Integration {connection.pk} has no tenant evidence and the database does not contain exactly one organization."
            )
        IntegrationConnection.objects.filter(pk=connection.pk).update(organization_id=organization_id)


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0015_custody_chain_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('packet', 'Packet'), ('session', 'Session'), ('payload', 'Payload')], max_length=16)),
                ('source_reference', models.CharField(max_length=160)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_by_label', models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationCaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_case_reference', models.CharField(blank=True, max_length=160)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('disabled', 'Disabled'), ('pending', 'Pending'), ('ready', 'Ready'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='disabled', max_length=16)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_connections', to='forensics.organization'),
        ),
        migrations.RunPython(backfill_integration_organizations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='integrationconnection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_connections', to='forensics.organization'),
        ),
        migrations.AddField(
            model_name='integrationcredential',
            name='secret_envelope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='integrationcredential',
            name='secret_key_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='integrationcredential',
            name='secret_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='integrationdelivery',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='integrationdelivery',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationdelivery',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='integrationdelivery',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='integrationdelivery',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationdelivery',
            name='lease_owner',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='integrationdelivery',
            name='max_attempts',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='integrationdelivery',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='operation_kind',
            field=models.CharField(choices=[('analysis', 'Analysis'), ('capture_log_import', 'Capture log import'), ('zeek_log_import', 'Zeek log import')], db_index=True, default='analysis', max_length=32),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='system_name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='processing_path',
            field=models.CharField(default='postgres-worker', max_length=32),
        ),
        migrations.AddIndex(
            model_name='integrationconnection',
            index=models.Index(fields=['organization', 'status'], name='netra_integration_org_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationdelivery',
            index=models.Index(fields=['result', 'next_attempt_at'], name='netra_delivery_ready_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationdelivery',
            index=models.Index(fields=['result', 'lease_expires_at'], name='netra_delivery_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'system_name'), name='netra_integration_org_name_uniq'),
        ),
        migrations.AddField(
            model_name='analysisreference',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_references', to='forensics.case'),
        ),
        migrations.AddField(
            model_name='analysisreference',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netra_analysis_references', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisreference',
            name='evidence_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_references', to='forensics.evidencefile'),
        ),
        migrations.AddField(
            model_name='analysisreference',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_references', to='forensics.organization'),
        ),
        migrations.AddField(
            model_name='analysisreference',
            name='processing_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_references', to='forensics.processingjob'),
        ),
        migrations.AddField(
            model_name='integrationcaselink',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_links', to='forensics.case'),
        ),
        migrations.AddField(
            model_name='integrationcaselink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netra_integration_case_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integrationcaselink',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_links', to='forensics.integrationconnection'),
        ),
        migrations.AddField(
            model_name='integrationcaselink',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_case_links', to='forensics.organization'),
        ),
        migrations.AddIndex(
            model_name='analysisreference',
            index=models.Index(fields=['organization', 'case', 'kind'], name='netra_analysis_ref_org_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisreference',
            index=models.Index(fields=['processing_job', 'kind'], name='netra_analysis_ref_job_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisreference',
            constraint=models.UniqueConstraint(fields=('case', 'processing_job', 'kind', 'source_reference'), name='netra_analysis_ref_unique'),
        ),
        migrations.AddIndex(
            model_name='integrationcaselink',
            index=models.Index(fields=['organization', 'sync_status', 'updated_at'], name='netra_case_link_sync_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationcaselink',
            constraint=models.UniqueConstraint(fields=('case', 'integration'), name='netra_case_integration_uniq'),
        ),
    ]
