# Generated by Django 5.2.16 on 2026-08-13 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0017_phase8_security_closure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chain_index', models.PositiveBigIntegerField()),
                ('recorded_at', models.DateTimeField()),
                ('actor_label', models.CharField(max_length=160)),
                ('actor_email', models.CharField(blank=True, max_length=320)),
                ('actor_role', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=160)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=160)),
                ('before_json', models.JSONField(blank=True, default=dict)),
                ('after_json', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('event_hash', models.CharField(max_length=64)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_audit_events', to='forensics.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'chain_index'], name='netra_admin_audit_chain_idx'), models.Index(fields=['organization', 'recorded_at'], name='netra_admin_audit_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'chain_index'), name='netra_admin_audit_chain_unique')],
            },
        ),
    ]
