# Generated by Django 5.2.16 on 2026-08-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0018_admin_audit_chain'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='netra_one_admin_per_org',
        ),
    ]
