# Generated by Django 5.2.16 on 2026-08-13 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0019_multiple_administrators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRevocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('revoked_by_label', models.CharField(blank=True, max_length=160)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_revocations', to='forensics.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='netra_session_revocation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'revoked_at'], name='netra_revocation_org_idx')],
            },
        ),
    ]
