from django.db import migrations


PARTITION_ACCESS_LOGS = r"""
DO $netra$
DECLARE
    month_start timestamptz;
    month_end timestamptz;
    partition_name text;
    source_rows bigint;
    copied_rows bigint;
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_partitioned_table partitioned
        WHERE partitioned.partrelid = 'public.forensics_accesslog'::regclass
    ) THEN
        RETURN;
    END IF;

    LOCK TABLE public.forensics_accesslog IN ACCESS EXCLUSIVE MODE;
    SELECT count(*) INTO source_rows FROM public.forensics_accesslog;

    CREATE TABLE public.forensics_accesslog_partitioned (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL,
        user_label varchar(160) NOT NULL,
        role varchar(32) NOT NULL,
        action varchar(160) NOT NULL,
        resource_type varchar(80) NOT NULL,
        resource_id varchar(160) NOT NULL,
        result varchar(32) NOT NULL,
        ip_address inet NULL,
        user_id integer NULL,
        case_id varchar(64) NULL,
        organization_id uuid NOT NULL,
        CONSTRAINT netra_access_partitioned_pk PRIMARY KEY (id, created_at)
    ) PARTITION BY RANGE (created_at);

    FOR offset_months IN -18..6 LOOP
        month_start := date_trunc('month', now()) + make_interval(months => offset_months);
        month_end := month_start + interval '1 month';
        partition_name := format('forensics_accesslog_y%sm%s', to_char(month_start, 'YYYY'), to_char(month_start, 'MM'));
        EXECUTE format(
            'CREATE TABLE public.%I PARTITION OF public.forensics_accesslog_partitioned FOR VALUES FROM (%L) TO (%L)',
            partition_name,
            month_start,
            month_end
        );
    END LOOP;
    CREATE TABLE public.forensics_accesslog_default
        PARTITION OF public.forensics_accesslog_partitioned DEFAULT;

    INSERT INTO public.forensics_accesslog_partitioned (
        id, created_at, updated_at, user_label, role, action, resource_type,
        resource_id, result, ip_address, user_id, case_id, organization_id
    )
    SELECT
        id, created_at, updated_at, user_label, role, action, resource_type,
        resource_id, result, ip_address, user_id, case_id, organization_id
    FROM public.forensics_accesslog;

    SELECT count(*) INTO copied_rows FROM public.forensics_accesslog_partitioned;
    IF copied_rows <> source_rows THEN
        RAISE EXCEPTION 'AccessLog partition copy mismatch: source %, copied %', source_rows, copied_rows;
    END IF;

    PERFORM setval(
        pg_get_serial_sequence('public.forensics_accesslog_partitioned', 'id'),
        COALESCE((SELECT max(id) FROM public.forensics_accesslog_partitioned), 1),
        source_rows > 0
    );

    ALTER TABLE public.forensics_accesslog RENAME TO forensics_accesslog_unpartitioned;
    ALTER TABLE public.forensics_accesslog_partitioned RENAME TO forensics_accesslog;
    DROP TABLE public.forensics_accesslog_unpartitioned;

    ALTER TABLE public.forensics_accesslog
        ADD CONSTRAINT netra_access_user_fk
        FOREIGN KEY (user_id) REFERENCES public.auth_user(id)
        DEFERRABLE INITIALLY DEFERRED;
    ALTER TABLE public.forensics_accesslog
        ADD CONSTRAINT netra_access_case_fk
        FOREIGN KEY (case_id) REFERENCES public.forensics_case(id)
        DEFERRABLE INITIALLY DEFERRED;
    ALTER TABLE public.forensics_accesslog
        ADD CONSTRAINT netra_access_org_fk
        FOREIGN KEY (organization_id) REFERENCES public.forensics_organization(id)
        DEFERRABLE INITIALLY DEFERRED;

    CREATE INDEX netra_access_org_created_idx
        ON public.forensics_accesslog (organization_id, created_at);
    CREATE INDEX netra_access_org_case_idx
        ON public.forensics_accesslog (organization_id, case_id, created_at);
    CREATE INDEX netra_access_created_idx
        ON public.forensics_accesslog (created_at);

    ALTER TABLE public.forensics_accesslog ENABLE ROW LEVEL SECURITY;
    REVOKE ALL ON TABLE public.forensics_accesslog FROM PUBLIC;
    -- anon, authenticated and service_role are Supabase's roles. They exist
    -- on the deployment this migration is written for and not in a plain
    -- PostgreSQL, so each is revoked only if present. Skipping a role that
    -- does not exist grants nothing; failing the migration over it would mean
    -- the schema could never be proved anywhere but Supabase.
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON TABLE public.forensics_accesslog FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON TABLE public.forensics_accesslog FROM authenticated;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
        REVOKE ALL ON TABLE public.forensics_accesslog FROM service_role;
    END IF;
END
$netra$;

CREATE OR REPLACE FUNCTION public.netra_reject_access_log_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $function$
BEGIN
    IF current_setting('netra.access_log_maintenance', true) IS DISTINCT FROM 'on' THEN
        RAISE EXCEPTION 'AccessLog rows are append-only';
    END IF;
    -- A BEFORE UPDATE trigger returning OLD tells PostgreSQL to write OLD back,
    -- which discards the change silently rather than refusing it. That turned
    -- the maintenance window into a no-op: retention was permitted to run and
    -- then had nothing to act on, with no error to explain why. DELETE is the
    -- case where OLD is the right answer.
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END
$function$;

DROP TRIGGER IF EXISTS netra_access_log_append_only ON public.forensics_accesslog;
CREATE TRIGGER netra_access_log_append_only
BEFORE UPDATE OR DELETE ON public.forensics_accesslog
FOR EACH ROW EXECUTE FUNCTION public.netra_reject_access_log_mutation();

CREATE OR REPLACE FUNCTION public.netra_maintain_access_log_partitions(retention_days integer)
RETURNS TABLE(created_partitions integer, dropped_partitions integer, deleted_rows bigint)
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $function$
DECLARE
    month_start timestamptz;
    month_end timestamptz;
    partition_name text;
    cutoff timestamptz;
    affected bigint;
BEGIN
    IF retention_days < 1 OR retention_days > 3650 THEN
        RAISE EXCEPTION 'retention_days must be between 1 and 3650';
    END IF;
    IF NOT pg_try_advisory_xact_lock(718204, 23001) THEN
        RAISE EXCEPTION 'AccessLog maintenance is already running';
    END IF;

    created_partitions := 0;
    dropped_partitions := 0;
    deleted_rows := 0;
    cutoff := now() - make_interval(days => retention_days);

    FOR offset_months IN 0..6 LOOP
        month_start := date_trunc('month', now()) + make_interval(months => offset_months);
        month_end := month_start + interval '1 month';
        partition_name := format('forensics_accesslog_y%sm%s', to_char(month_start, 'YYYY'), to_char(month_start, 'MM'));
        IF to_regclass(format('public.%I', partition_name)) IS NULL THEN
            EXECUTE format(
                'CREATE TABLE public.%I PARTITION OF public.forensics_accesslog FOR VALUES FROM (%L) TO (%L)',
                partition_name,
                month_start,
                month_end
            );
            created_partitions := created_partitions + 1;
        END IF;
    END LOOP;

    PERFORM set_config('netra.access_log_maintenance', 'on', true);
    DELETE FROM public.forensics_accesslog WHERE created_at < cutoff;
    GET DIAGNOSTICS deleted_rows = ROW_COUNT;

    FOR offset_months IN -180..-1 LOOP
        month_start := date_trunc('month', now()) + make_interval(months => offset_months);
        month_end := month_start + interval '1 month';
        EXIT WHEN month_end > cutoff;
        partition_name := format('forensics_accesslog_y%sm%s', to_char(month_start, 'YYYY'), to_char(month_start, 'MM'));
        IF to_regclass(format('public.%I', partition_name)) IS NOT NULL THEN
            EXECUTE format('DROP TABLE public.%I', partition_name);
            dropped_partitions := dropped_partitions + 1;
        END IF;
    END LOOP;

    RETURN NEXT;
END
$function$;

REVOKE ALL ON FUNCTION public.netra_reject_access_log_mutation() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.netra_maintain_access_log_partitions(integer) FROM PUBLIC;
"""


def partition_access_logs(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    # params=None, not the default empty tuple. With a tuple psycopg still
    # runs the statement through mogrify, and this SQL is full of literal
    # per-cent signs — format('%I', ...) in the PL/pgSQL bodies — which
    # mogrify reads as placeholders and rejects.
    schema_editor.execute(PARTITION_ACCESS_LOGS, params=None)


class Migration(migrations.Migration):
    dependencies = [("forensics", "0022_seed_permission_catalogue")]

    operations = [migrations.RunPython(partition_access_logs, migrations.RunPython.noop)]
