# Generated by Django 5.2.16 on 2026-08-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0025_two_role_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='held_credential',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='held_credential_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
