"""Handing an account over when the officer cannot receive mail.

An invitation is a link and nothing else, so a deployment whose messages do not
reach its officers creates accounts nobody can enter. The password path exists
for that, and these tests hold the parts that make it trustworthy: the operator
chooses which path runs, the credential is still generated by Netra rather than
supplied, and a message that did not leave is never reported as though it did.
"""

from unittest.mock import patch

from django.test import TestCase, override_settings

from apps.forensics.models import UserProfile
from apps.forensics.services.administration import AdministrationProblem
from apps.forensics.services.admin_users import provision_account
from common.audit import ROLE_PERMISSIONS, Actor
from common.credential_mail import Delivery, send_credential
from common.supabase_admin import SupabaseAdminUser
from common.tenancy import netra_organization


IDENTITY = SupabaseAdminUser(
    id="9d1f0a7c-2c53-4c1e-9a5f-6b0f1d2e3a44",
    email="officer@netra.test",
    invited_at="",
    email_confirmed_at="",
    last_sign_in_at="",
    mfa_state="unenrolled",
)


def _refusal(call):
    """Return the AdministrationProblem a call raises.

    Not assertRaises: AdministrationProblem is a frozen dataclass, so unittest
    cannot attach a traceback to it and the context manager fails before the
    assertion is ever reached.
    """
    try:
        call()
    except AdministrationProblem as problem:
        return problem
    raise AssertionError("the call was expected to be refused and was not")


def _admin(organization):
    """A station head with a row, not just a token.

    require_privileged_admin ends by reading the actor's UserProfile, so an
    Actor assembled in memory is refused however many permissions it claims.
    That is the point of the check: authority comes from the database rather
    than from anything the caller can assert.
    """
    from datetime import UTC, datetime

    from django.contrib.auth import get_user_model

    from apps.forensics.models import Role

    User = get_user_model()
    user = User.objects.create_user(username="head@netra.test", email="head@netra.test", is_active=True)
    UserProfile.objects.create(
        user=user,
        organization=organization,
        role=UserProfile.Role.ADMIN,
        role_ref=Role.objects.get(organization=organization, slug="admin"),
    )
    actor = Actor(
        user="head@netra.test",
        role="Admin",
        authenticated=True,
        django_user_id=user.id,
        organization_id=organization.id,
        aal="aal2",
        factor_verified_at=datetime.now(UTC),
        permissions=frozenset(ROLE_PERMISSIONS["Admin"]),
    )
    return actor


@override_settings(
    NETRA_AUTH_PROVIDER="supabase",
    NETRA_AUTH_INVITATIONS_ENABLED=True,
    NETRA_AUTH_INVITE_REDIRECT_URL="https://netra.example/auth/invite",
    NETRA_CREDENTIAL_EMAIL_ENABLED=False,
)
class DeliveryChoiceTests(TestCase):
    def setUp(self):
        self.organization = netra_organization()
        self.actor = _admin(self.organization)

    def _create(self, **kwargs):
        return provision_account(
            actor=self.actor,
            organization=self.organization,
            email=kwargs.pop("email", "officer@netra.test"),
            name="Officer",
            role="investigator",
            department="Cyber Cell",
            reason="Issuing an account for the demonstration.",
            **kwargs,
        )

    @patch("apps.forensics.services.admin_users.create_user", return_value=IDENTITY)
    def test_password_delivery_returns_a_credential_without_touching_invite(self, create):
        with patch("apps.forensics.services.admin_users.invite_user") as invite:
            change = self._create(delivery="password")

        invite.assert_not_called()
        create.assert_called_once()
        self.assertTrue(change.password)
        self.assertEqual(change.delivery, "password")

    @patch("apps.forensics.services.admin_users.invite_user", return_value=IDENTITY)
    def test_invite_delivery_sends_a_link_and_no_credential(self, invite):
        with patch("apps.forensics.services.admin_users.create_user") as create:
            change = self._create(delivery="invite")

        create.assert_not_called()
        invite.assert_called_once()
        self.assertEqual(change.password, "")
        self.assertEqual(change.delivery, "invite")

    @patch("apps.forensics.services.admin_users.create_user", return_value=IDENTITY)
    def test_an_administrator_still_cannot_choose_the_credential(self, _create):
        """The reason is attribution rather than strength. An administrator who
        knows the password an officer signs in with is indistinguishable from
        that officer in the access log, which is most of what the log is for."""
        problem = _refusal(lambda: self._create(delivery="password", password="chosen-by-the-admin"))

        self.assertEqual(problem.code, "password_not_accepted")

    def test_an_unknown_delivery_is_refused(self):
        problem = _refusal(lambda: self._create(delivery="carrier-pigeon"))

        self.assertEqual(problem.code, "invalid_delivery")

    @override_settings(NETRA_AUTH_INVITATIONS_ENABLED=False)
    def test_asking_for_an_invitation_where_none_can_be_sent_is_refused(self):
        """Better to refuse than to create an account whose only route in is a
        message this deployment cannot send."""
        problem = _refusal(lambda: self._create(delivery="invite"))

        self.assertEqual(problem.code, "invitations_disabled")


@override_settings(
    NETRA_AUTH_PROVIDER="supabase",
    NETRA_AUTH_INVITATIONS_ENABLED=True,
    NETRA_CREDENTIAL_EMAIL_ENABLED=False,
)
class RotationTests(TestCase):
    def setUp(self):
        self.organization = netra_organization()
        self.actor = _admin(self.organization)

    def _create(self, email):
        return provision_account(
            actor=self.actor,
            organization=self.organization,
            email=email,
            name="Officer",
            role="investigator",
            department="Cyber Cell",
            reason="Issuing an account for the demonstration.",
            delivery="password",
        )

    @patch("apps.forensics.services.admin_users.create_user", return_value=IDENTITY)
    def test_a_credential_is_temporary_by_default(self, _create):
        change = self._create("rotates@netra.test")

        self.assertTrue(change.profile.must_change_password)

    @override_settings(NETRA_ADMIN_HELD_PASSWORDS_ENABLED=True)
    @patch("apps.forensics.services.admin_users.create_user", return_value=IDENTITY)
    def test_a_deployment_may_hold_the_credential_instead(self, _create):
        """Defensible where one desk issues every account, and only there. The
        cost is that two people know the credential for as long as it stands."""
        change = self._create("held@netra.test")

        self.assertFalse(change.profile.must_change_password)


@override_settings(EMAIL_BACKEND="django.core.mail.backends.locmem.EmailBackend")
class CredentialMailTests(TestCase):
    """A message that did not leave must never be reported as though it did.

    The locmem backend is set for the whole class rather than per test. These
    cases have to name a mail host to reach the code under test, and a suite
    that can open a socket to whatever host a test invents will one day wait on
    one instead of failing — which is how this file first held up a release.
    """

    def test_nothing_is_sent_while_the_feature_is_off(self):
        result = send_credential(
            email="officer@netra.test", name="Officer", password="x", must_change_password=True
        )

        self.assertFalse(result.sent)
        self.assertEqual(result.reason, "credential_email_disabled")

    @override_settings(NETRA_CREDENTIAL_EMAIL_ENABLED=True, EMAIL_HOST="")
    def test_an_unconfigured_host_says_so_rather_than_claiming_delivery(self):
        result = send_credential(
            email="officer@netra.test", name="Officer", password="x", must_change_password=True
        )

        self.assertFalse(result.sent)
        self.assertEqual(result.reason, "no_mail_host_configured")

    @override_settings(
        NETRA_CREDENTIAL_EMAIL_ENABLED=True,
        EMAIL_HOST="smtp.example",
        DEFAULT_FROM_EMAIL="netra@example",
        EMAIL_BACKEND="django.core.mail.backends.locmem.EmailBackend",
    )
    def test_a_sent_message_carries_the_credential_and_the_address(self):
        from django.core import mail

        result = send_credential(
            email="officer@netra.test",
            name="Officer",
            password="Handover-Credential-42",
            must_change_password=True,
        )

        self.assertTrue(result.sent)
        self.assertEqual(len(mail.outbox), 1)
        self.assertIn("Handover-Credential-42", mail.outbox[0].body)
        self.assertEqual(mail.outbox[0].to, ["officer@netra.test"])

    @override_settings(
        NETRA_CREDENTIAL_EMAIL_ENABLED=True,
        EMAIL_HOST="smtp.example",
        DEFAULT_FROM_EMAIL="netra@example",
    )
    def test_a_refusing_host_is_reported_as_a_failure_not_an_exception(self):
        """The account already exists by this point. A mail fault must not
        surface as a 500 over an account that was created successfully."""
        with patch("common.credential_mail.EmailMessage.send", side_effect=OSError("refused")):
            result = send_credential(
                email="officer@netra.test", name="Officer", password="x", must_change_password=True
            )

        self.assertFalse(result.sent)
        self.assertEqual(result.reason, "mail_host_refused")

    @override_settings(
        NETRA_AUTH_PROVIDER="supabase",
        NETRA_AUTH_INVITATIONS_ENABLED=True,
        NETRA_CREDENTIAL_EMAIL_ENABLED=True,
        EMAIL_HOST="smtp.example",
        DEFAULT_FROM_EMAIL="netra@example",
        EMAIL_BACKEND="django.core.mail.backends.locmem.EmailBackend",
    )
    @patch("apps.forensics.services.admin_users.create_user", return_value=IDENTITY)
    def test_a_mail_failure_leaves_the_account_standing(self, _create):
        organization = netra_organization()
        # Patched where it is used, not where it is defined. admin_users binds
        # the name at import, so patching common.credential_mail leaves the
        # bound reference alone and the real sender runs — which on a host with
        # no route to smtp.example means the suite waits on a socket.
        with patch(
            "apps.forensics.services.admin_users.send_credential",
            return_value=Delivery(sent=False, reason="mail_host_refused"),
        ) as sender:
            change = provision_account(
                actor=_admin(organization),
                organization=organization,
                email="stands@netra.test",
                name="Officer",
                role="investigator",
                department="Cyber Cell",
                reason="Issuing an account for the demonstration.",
                delivery="password",
            )

        # Asserted so the test cannot pass by patching a name nothing calls.
        sender.assert_called_once()
        self.assertTrue(UserProfile.objects.filter(user__username="stands@netra.test").exists())
        self.assertTrue(change.password, "the credential must still reach the operator on screen")
        self.assertFalse(change.email_sent)
        self.assertEqual(change.email_failure, "mail_host_refused")
