from django.urls import path

from apps.forensics.route_policies import attach_route_policies
from apps.forensics.api import admin_console as admin_console_views
from apps.forensics.api import analysis as analysis_views
from apps.forensics.api import authentication as auth_views
from apps.forensics.api import capture as capture_views
from apps.forensics.api import cases as case_views
from apps.forensics.api import compliance as compliance_views
from apps.forensics.api import evidence as evidence_views
from apps.forensics.api import features as feature_views
from apps.forensics.api import integrations as integration_views
from apps.forensics.api import events as event_views
from apps.forensics.api import operations as operation_views
from apps.forensics.api import reports as report_views


urlpatterns = [
    path("health", operation_views.health),
    path("setup/status", operation_views.setup_status),
    path("setup/admin", operation_views.setup_admin),
    path("auth/login", auth_views.auth_login),
    path("auth/refresh", auth_views.auth_refresh),
    path("auth/logout", auth_views.auth_logout),
    path("auth/me", auth_views.auth_me),
    path("capabilities", operation_views.capabilities),
    path("users", auth_views.users),
    path("users/<str:user_id>", auth_views.user_detail),
    path("admin/organizations/<uuid:organization_id>/admin-transfer", auth_views.admin_transfer),
    path("admin/v1/session", admin_console_views.admin_session),
    path("admin/v1/directory", admin_console_views.admin_directory),
    path("admin/v1/audit/verify", admin_console_views.admin_audit_verify),
    path("cases", case_views.cases),
    path("cases/<str:case_id>", case_views.case_detail),
    path("cases/<str:case_id>/workspace", case_views.case_workspace),
    path("workspaces/<uuid:route_ref>/status", case_views.case_workspace_status),
    path("workspaces/<uuid:route_ref>", case_views.case_workspace_by_route),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/summary", analysis_views.summary),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/traffic-timeline", analysis_views.traffic_timeline),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/protocol-distribution", analysis_views.protocol_distribution),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/alerts", analysis_views.alerts),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/alerts/<str:alert_id>/status", analysis_views.alert_status),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/packets", analysis_views.packets),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/packets/<str:packet_id>", analysis_views.packet_detail),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/sessions", analysis_views.sessions),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/sessions/<str:session_id>", analysis_views.session_detail),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/sessions/<str:session_id>/timeline", analysis_views.session_timeline),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/decoder", analysis_views.decoder),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/decoder/<str:protocol>", analysis_views.decoder_protocol),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/payloads", analysis_views.payloads),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/payloads/<str:finding_id>", analysis_views.payload_detail),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/detections", analysis_views.detections),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/detections/<str:match_id>/status", analysis_views.detection_status),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/anomalies", analysis_views.anomalies),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/anomalies/baseline-comparison", analysis_views.anomaly_baseline),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/anomalies/risk-timeline", analysis_views.anomaly_risk_timeline),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/graph", analysis_views.graph),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/graph/nodes/<str:node_id>", analysis_views.graph_node),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/graph/attack-path", analysis_views.graph_attack_path),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/references/<str:kind>", feature_views.analysis_references),
    path("workspaces/<uuid:route_ref>/imports/capture-log", feature_views.capture_log_import),
    path("workspaces/<uuid:route_ref>/imports/zeek-log", feature_views.zeek_log_import),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/search", feature_views.scoped_search),
    path("workspaces/<uuid:route_ref>/capture/jobs/<str:job_id>/stop", feature_views.capture_stop),
    path("workspaces/<uuid:route_ref>/integrations", integration_views.workspace_connections),
    path("workspaces/<uuid:route_ref>/integrations/<str:integration_id>/link", integration_views.link_case),
    path("workspaces/<uuid:route_ref>/analysis/jobs/<str:job_id>/integrations/<str:integration_id>/alerts", integration_views.send_alerts),
    path("cases/<str:case_id>/summary", case_views.case_light_summary),
    path("cases/<str:case_id>/light-summary", case_views.case_light_summary),
    path("cases/<str:case_id>/charts", case_views.case_charts),
    path("cases/<str:case_id>/tabs/<str:tab_name>", case_views.case_tab),
    path("cases/<str:case_id>/reports", report_views.case_reports),
    path("cases/<str:case_id>/flags", case_views.case_flags),
    path("cases/<str:case_id>/flags/<str:flag>", case_views.case_flag_detail),
    path("cases/<str:case_id>/links", case_views.case_links),
    path("cases/<str:case_id>/links/<str:link_id>", case_views.case_link_detail),
    path("cases/<str:case_id>/anomaly-explanation", case_views.case_anomaly_explanation),
    path("cases/<str:case_id>/notes", case_views.case_notes),
    path("cases/<str:case_id>/history", case_views.case_history),
    path("cases/<str:case_id>/custody-ledger", compliance_views.custody_ledger),
    path("cases/<str:case_id>/custody-ledger/verify", compliance_views.custody_verify),
    path("cases/<str:case_id>/custody-ledger/export", compliance_views.custody_export),
    path("cases/<str:case_id>/linked-evidence", evidence_views.case_linked_evidence),
    path("cases/<str:case_id>/members", case_views.case_members),
    path("cases/<str:case_id>/members/<str:member_id>", case_views.case_member_detail),
    path("cases/<str:case_id>/linked-packets", case_views.link_stub),
    path("cases/<str:case_id>/linked-sessions", case_views.link_stub),
    path("cases/<str:case_id>/linked-payloads", case_views.link_stub),
    path("evidence/normalize-preview", evidence_views.evidence_normalize_preview),
    path("evidence/upload-sessions", evidence_views.evidence_upload_sessions),
    path("evidence/upload-sessions/<uuid:upload_session_id>", evidence_views.evidence_upload_session_detail),
    path("evidence/upload-sessions/<uuid:upload_session_id>/finalize", evidence_views.evidence_upload_session_finalize),
    path("evidence/upload", evidence_views.evidence_upload),
    path("evidence/<str:evidence_id>/manifest", evidence_views.evidence_manifest),
    path("evidence/<str:evidence_id>/verify-integrity", evidence_views.evidence_verify_integrity),
    path("evidence/<str:evidence_id>/download", evidence_views.evidence_download),
    path("capture/interfaces", capture_views.capture_interfaces),
    path("capture/live/start", capture_views.capture_live_start),
    path("capture/live/stop", capture_views.capture_live_stop),
    path("capture/live/status/<str:job_id>", capture_views.capture_live_status),
    path("capture/replay/start", capture_views.capture_replay_start),
    path("capture/replay/stop", capture_views.capture_replay_stop),
    path("capture/replay/<str:job_id>/stop", capture_views.capture_replay_stop),
    path("capture/replay/status/<str:job_id>", capture_views.capture_replay_status),
    path("capture/replay/<str:job_id>/status", capture_views.capture_replay_status),
    path("capture/live/<str:job_id>/stop", capture_views.capture_live_stop),
    path("capture/live/<str:job_id>/status", capture_views.capture_live_status),
    path("capture/log-import", capture_views.capture_log_import),
    path("sensors", capture_views.sensors),
    path("sensors/register", capture_views.sensor_register),
    path("sensors/<str:sensor_id>", capture_views.sensor_detail),
    path("sensors/<str:sensor_id>/enable", capture_views.sensor_enable),
    path("sensors/<str:sensor_id>/disable", capture_views.sensor_disable),
    path("sensors/<str:sensor_id>/history", capture_views.sensor_history),
    path("sensors/<str:sensor_id>/captures", capture_views.sensor_captures),
    path("sensors/<str:sensor_id>/heartbeat", capture_views.sensor_heartbeat),
    path("sensors/<str:sensor_id>/commands/next", capture_views.sensor_next_command),
    path("sensors/<str:sensor_id>/chunks", capture_views.sensor_chunk_upload),
    path("sensors/<str:sensor_id>/captures/<str:job_id>/complete", capture_views.sensor_capture_complete),
    path("sensors/<str:sensor_id>/captures/<str:job_id>/fail", capture_views.sensor_capture_fail),
    path("sensor-groups", capture_views.sensor_groups),
    path("sensor-groups/<str:group_id>", capture_views.sensor_group_detail),
    path("capture-schedules", capture_views.capture_schedules),
    path("capture-schedules/<str:schedule_id>", capture_views.capture_schedule_detail),
    path("capture-schedules/<str:schedule_id>/run-now", capture_views.capture_schedule_run_now),
    path("capture-schedules/<str:schedule_id>/history", capture_views.capture_schedule_history),
    path("events", operation_views.operational_events),
    path("events/stream", event_views.event_stream),
    path("logs/import/zeek", capture_views.zeek_log_import),
    path("jobs/<str:job_id>/status", operation_views.job_status),
    path("jobs/<str:job_id>/events", operation_views.job_events),
    path("jobs/<str:job_id>/cancel", operation_views.job_cancel),
    path("system/workers", operation_views.system_workers),
    path("system/health/deep", operation_views.system_health_deep),
    path("system/metrics", operation_views.system_metrics),
    path("system/storage", operation_views.system_storage),
    path("system/indexes", operation_views.system_indexes),
    path("system/kafka", operation_views.system_kafka),
    path("system/realtime", operation_views.system_realtime),
    path("system/kafka/lag", operation_views.system_kafka_lag),
    path("system/capacity", operation_views.system_capacity),
    path("system/throughput", operation_views.system_throughput),
    path("system/indexes/retention", operation_views.system_index_retention),
    path("system/database", operation_views.system_database),
    path("system/sensors", capture_views.sensors),
    path("system/dead-letter", operation_views.dead_letter),
    path("system/dead-letter/<str:event_id>/retry", operation_views.dead_letter_retry),
    path("system/dead-letter/<str:event_id>/ignore", operation_views.dead_letter_ignore),
    path("jobs/<str:job_id>/reprocess", operation_views.job_reprocess),
    path("search", operation_views.search),
    path("dashboard/summary", analysis_views.legacy_summary),
    path("dashboard/traffic-timeline", analysis_views.legacy_traffic_timeline),
    path("dashboard/protocol-distribution", analysis_views.legacy_protocol_distribution),
    path("alerts", analysis_views.legacy_alerts),
    path("alerts/<str:alert_id>/status", analysis_views.legacy_alert_status),
    path("packets", analysis_views.legacy_packets),
    path("packets/<str:packet_id>", analysis_views.legacy_packet_detail),
    path("sessions", analysis_views.legacy_sessions),
    path("sessions/<str:session_id>", analysis_views.legacy_session_detail),
    path("sessions/<str:session_id>/timeline", analysis_views.legacy_session_timeline),
    path("decoder/summary", analysis_views.legacy_decoder),
    path("decoder/<str:protocol>", analysis_views.legacy_decoder_protocol),
    path("payloads", analysis_views.legacy_payloads),
    path("payloads/<str:finding_id>", analysis_views.legacy_payload_detail),
    path("detection/rules", operation_views.detection_rules),
    path("detection/matches", analysis_views.legacy_detections),
    path("detection/matches/<str:match_id>/status", analysis_views.legacy_detection_status),
    path("anomalies", analysis_views.legacy_anomalies),
    path("anomalies/baseline-comparison", analysis_views.legacy_anomaly_baseline),
    path("anomalies/risk-timeline", analysis_views.legacy_anomaly_risk_timeline),
    path("graph", analysis_views.legacy_graph),
    path("graph/nodes/<str:node_id>", analysis_views.legacy_graph_node),
    path("graph/attack-path", analysis_views.legacy_graph_attack_path),
    path("reports/<str:case_id>/preview", report_views.report_preview),
    path("reports", report_views.reports),
    path("reports/<str:case_id>/generate-pdf", report_views.report_generate),
    path("reports/<str:case_id>/generate", report_views.report_generate),
    path("reports/<str:report_id>/download", report_views.report_download),
    path("exports", report_views.exports),
    path("exports/<str:export_id>", report_views.export_detail),
    path("exports/<str:export_id>/download", report_views.export_download),
    path("integrations", integration_views.connections),
    path("integrations/siem/export", report_views.siem_export),
    path("integrations/<str:integration_id>", integration_views.connection_detail),
    path("integrations/<str:integration_id>/credential", integration_views.credential),
    path("integrations/<str:integration_id>/sync", integration_views.external_sync),
    path("integrations/<str:integration_id>/test", integration_views.test_delivery),
    path("integrations/<str:integration_id>/deliveries", integration_views.deliveries),
    path("integrations/<str:integration_id>/deliveries/<str:delivery_id>/retry", integration_views.retry_delivery),
    path("compliance/checklist", compliance_views.compliance_checklist),
    path("compliance/roles", compliance_views.compliance_roles),
    path("compliance/security-posture", compliance_views.security_posture),
    path("audit/access-logs", compliance_views.access_logs),
    path("retention/policy", capture_views.retention_policy),
    path("retention/preview", capture_views.retention_preview_view),
    path("retention/execute", capture_views.retention_execute),
    path("retention/runs", capture_views.retention_runs),
    path("cases/<str:case_id>/legal-hold", compliance_views.case_legal_hold),
    path("cases/<str:case_id>/legal-review/checklist", compliance_views.case_legal_review_checklist),
    path("system/incident-readiness", operation_views.system_incident_readiness),
    path("system/deployment-readiness", operation_views.system_deployment_readiness),
    path("system/status-matrix", operation_views.system_status_matrix),
    path("ml/model-status", operation_views.ml_model_status),
    path("audit/export", compliance_views.audit_export),
]

attach_route_policies(urlpatterns)
